//=========================================
// Import original Rmmz if no edits.
import {
  ColorFilter,
  JsonEx,
  Point,
  Rectangle,
  ScreenSprite,
  Sprite,
  Stage,
  Tilemap,
  TilingSprite,
  Video,
  Weather,
  Window,
  WindowLayer
} from './rmmz_core'
import {
  AudioManager,
  BattleManager,
  ColorManager,
  EffectManager,
  FontManager,
  ImageManager,
  SceneManager,
  SoundManager,
  TextManager
} from './rmmz_managers'
import {
  Game_Action,
  Game_ActionResult,
  Game_Actor,
  Game_Battler,
  Game_BattlerBase,
  Game_Character,
  Game_CharacterBase,
  Game_CommonEvent,
  Game_Enemy,
  Game_Followers,
  Game_Message,
  Game_Picture,
  Game_Troop,
  Game_Unit
} from './rmmz_objects'
import {
  Scene_Battle,
  Scene_Debug,
  Scene_Equip,
  Scene_File,
  Scene_Gameover,
  Scene_Item,
  Scene_ItemBase,
  Scene_Map,
  Scene_MenuBase,
  Scene_Message,
  Scene_Name,
  Scene_Shop,
  Scene_Skill,
  Scene_Status
} from './rmmz_scenes'
import {
  Sprite_Animation,
  Sprite_AnimationMV,
  Sprite_Balloon,
  Sprite_Battler,
  Sprite_Button,
  Sprite_Character,
  Sprite_Clickable,
  Sprite_Damage,
  Sprite_Destination,
  Sprite_Gauge,
  Sprite_Name,
  Sprite_Picture,
  Sprite_StateIcon,
  Sprite_StateOverlay,
  Sprite_Timer,
  Sprite_Weapon,
  Spriteset_Base,
  Spriteset_Battle,
  Spriteset_Map
} from './rmmz_sprites'
import {
  Window_ActorCommand,
  Window_Base,
  Window_BattleActor,
  Window_BattleEnemy,
  Window_BattleItem,
  Window_BattleLog,
  Window_BattleSkill,
  Window_BattleStatus,
  Window_ChoiceList,
  Window_Command,
  Window_DebugEdit,
  Window_DebugRange,
  Window_EquipCommand,
  Window_EquipItem,
  Window_EquipSlot,
  Window_EquipStatus,
  Window_EventItem,
  Window_Gold,
  Window_Help,
  Window_HorzCommand,
  Window_ItemCategory,
  Window_ItemList,
  Window_MapName,
  Window_MenuActor,
  Window_MenuStatus,
  Window_Message,
  Window_NameBox,
  Window_NameEdit,
  Window_NameInput,
  Window_NumberInput,
  Window_PartyCommand,
  Window_SavefileList,
  Window_ScrollText,
  Window_Scrollable,
  Window_Selectable,
  Window_ShopBuy,
  Window_ShopCommand,
  Window_ShopNumber,
  Window_ShopSell,
  Window_ShopStatus,
  Window_SkillList,
  Window_SkillStatus,
  Window_SkillType,
  Window_Status,
  Window_StatusBase,
  Window_StatusEquip,
  Window_StatusParams
} from './rmmz_windows'
//=========================================
// Import edits not originals
import {
  // Core
  Utils,
  Graphics,
  WebAudio,
  Bitmap,
  Input,
  TouchInput,
  // Managers
  DataManager,
  ConfigManager,
  StorageManager,
  PluginManager,
  // Objects
  Game_Temp,
  Game_System,
  Game_Timer,
  Game_Switches,
  Game_Variables,
  Game_SelfSwitches,
  Game_Screen,
  Game_Item,
  Game_Actors,
  Game_Party,
  Game_Map,
  Game_Player,
  Game_Follower,
  Game_Vehicle,
  Game_Event,
  Game_Interpreter,
  // Scenes
  Scene_Base,
  Scene_Boot,
  Scene_Title,
  Scene_Menu,
  Scene_Options,
  Scene_GameEnd,
  Scene_Save,
  Scene_Load,
  // Windows
  Window_MenuCommand,
  Window_Options,
  Window_TitleCommand,
  Window_GameEnd,
  // Sprites
  Sprite_Enemy,
  Sprite_Battleback,
  Sprite_Actor
} from './edits/editsIndex'
//=========================================
// Import Custom
// **** Scene Controls ****
import { Scene_Controls } from './custom/scenes/controls/controls'
import { Scene_EditGamepad } from './custom/scenes/controls/editGamepad'
import { Scene_EditKeys } from './custom/scenes/controls/editKeys'
import { Window_Controls } from './custom/scenes/controls/windows/controls'
import { Window_EditKeys } from './custom/scenes/controls/windows/editKeys'
import { Window_EditGamepad } from './custom/scenes/controls/windows/editGamepad'
// **** Window Utility ****
import { Window_ConfirmCommand } from './custom/windows/utility/confirmCommand'
import { Window_Text } from './custom/windows/utility/text'

// Export everything to be placed onto the window in RMMZinject.jsx.
export {
  // Core
  Bitmap,
  ColorFilter,
  Graphics,
  Input,
  JsonEx,
  Point,
  Rectangle,
  ScreenSprite,
  Sprite,
  Stage,
  Tilemap,
  TilingSprite,
  TouchInput,
  Utils,
  Video,
  Weather,
  WebAudio,
  Window,
  WindowLayer,
  // Managers
  DataManager,
  AudioManager,
  BattleManager,
  ColorManager,
  ConfigManager,
  EffectManager,
  FontManager,
  ImageManager,
  PluginManager,
  SceneManager,
  SoundManager,
  StorageManager,
  TextManager,
  // Objects
  Game_Action,
  Game_ActionResult,
  Game_Actor,
  Game_Actors,
  Game_Battler,
  Game_BattlerBase,
  Game_Character,
  Game_CharacterBase,
  Game_CommonEvent,
  Game_Enemy,
  Game_Event,
  Game_Follower,
  Game_Followers,
  Game_Interpreter,
  Game_Item,
  Game_Map,
  Game_Message,
  Game_Party,
  Game_Picture,
  Game_Player,
  Game_Screen,
  Game_SelfSwitches,
  Game_Switches,
  Game_System,
  Game_Temp,
  Game_Timer,
  Game_Troop,
  Game_Unit,
  Game_Variables,
  Game_Vehicle,
  // Scenes
  Scene_Base,
  Scene_Battle,
  Scene_Boot,
  Scene_Debug,
  Scene_Equip,
  Scene_File,
  Scene_GameEnd,
  Scene_Gameover,
  Scene_Item,
  Scene_ItemBase,
  Scene_Load,
  Scene_Map,
  Scene_Menu,
  Scene_MenuBase,
  Scene_Message,
  Scene_Name,
  Scene_Options,
  Scene_Save,
  Scene_Shop,
  Scene_Skill,
  Scene_Status,
  Scene_Title,
  // Sprites
  Sprite_Actor,
  Sprite_Animation,
  Sprite_AnimationMV,
  Sprite_Balloon,
  Sprite_Battleback,
  Sprite_Battler,
  Sprite_Button,
  Sprite_Character,
  Sprite_Clickable,
  Sprite_Damage,
  Sprite_Destination,
  Sprite_Enemy,
  Sprite_Gauge,
  Sprite_Name,
  Sprite_Picture,
  Sprite_StateIcon,
  Sprite_StateOverlay,
  Sprite_Timer,
  Sprite_Weapon,
  Spriteset_Base,
  Spriteset_Battle,
  Spriteset_Map,
  // Windows
  Window_ActorCommand,
  Window_Base,
  Window_BattleActor,
  Window_BattleEnemy,
  Window_BattleItem,
  Window_BattleLog,
  Window_BattleSkill,
  Window_BattleStatus,
  Window_ChoiceList,
  Window_Command,
  Window_DebugEdit,
  Window_DebugRange,
  Window_EquipCommand,
  Window_EquipItem,
  Window_EquipSlot,
  Window_EquipStatus,
  Window_EventItem,
  Window_GameEnd,
  Window_Gold,
  Window_Help,
  Window_HorzCommand,
  Window_ItemCategory,
  Window_ItemList,
  Window_MapName,
  Window_MenuActor,
  Window_MenuCommand,
  Window_MenuStatus,
  Window_Message,
  Window_NameBox,
  Window_NameEdit,
  Window_NameInput,
  Window_NumberInput,
  Window_Options,
  Window_PartyCommand,
  Window_SavefileList,
  Window_ScrollText,
  Window_Scrollable,
  Window_Selectable,
  Window_ShopBuy,
  Window_ShopCommand,
  Window_ShopNumber,
  Window_ShopSell,
  Window_ShopStatus,
  Window_SkillList,
  Window_SkillStatus,
  Window_SkillType,
  Window_Status,
  Window_StatusBase,
  Window_StatusEquip,
  Window_StatusParams,
  Window_TitleCommand,
  // SCENE_CONTROLS
  Scene_Controls,
  Window_Controls,
  Scene_EditGamepad,
  Window_EditGamepad,
  Scene_EditKeys,
  Window_EditKeys,
  // WINDOW UTILITY
  Window_ConfirmCommand,
  Window_Text
}
